version: 2.1

jobs:
  build-and-analyze:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build, test and SonarCloud analysis
          command: |
            cd medical-appointment-system/backend
            mvn clean verify sonar:sonar \
              -Dsonar.token=${SONAR_TOKEN}

workflows:
  main:
    jobs:
      - build-and-analyze:
          context: SonarCloud
