package com.medical.entity;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_COMPLETED,
    SYSTEM_NOTIFICATION,
    MASS_NOTIFICATION,
    RESCHEDULE_REQUEST_PENDING,
    RESCHEDULE_REQUEST_APPROVED,
    RESCHEDULE_REQUEST_REJECTED,
    REVIEW_RECEIVED
}
